github.com:
    users:
        CJBuchel:
            oauth_token: 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
    git_protocol: https
    oauth_token: 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
    user: CJBuchel
